### PR TITLE
export functions

### LINKED ISSUE #13: Export math_helpers.ts
Hi

Could we export all the functions of `math_helpers.ts` ?

That way, we can use these functions without parsing again a gpx

Use case:
- I parse my gpx with default options
- My movingTime is not correct (example: I do a slow activity and the threshold is too high)
- I want to recalculate the duration

currently i can't because functions are not exported

A `export * from "./math_helpers"` in `index.ts` should be enough I guess ?

### PR DESCRIPTION
**Pull request by Its-Just-Nans**
Fix https://github.com/We-Gold/gpxjs/issues/13

### CODE REVIEW

**Comment by We-Gold** [comment]
A small note and a bigger one.

I think it's fine to keep XMLSerializationStrategy in the original file, and not move it to types.ts. It isn't used anywhere else, and it makes more sense in the context of the other code in the stringify file.

The current approach to exposing the math_helpers functions to the user would work, but I don't think it'll generalize very well if new calculations are added in the future since you need to write multiple new functions in the ParsedGPX class each time you create a new math helper.

One idea is to create a functional interface for math helpers that can be applied to ParsedGPX (since it's fine if not all of them can be, e.g. haversineDistance). 

Then, you could make a couple of "apply" methods for the ParsedGPX class that can take in any of the math helpers defined by the functional interface and run them on the specified track or route index. To make things easier with calculateDuration, you could make distance an optional parameter, and then if it isn't specified, call calculateDistance (in calculateDuration) on the points to calculate that intermediate result.

That could look something like this:

```ts
export class ParsedGPX {
    ...

    applyToTrack<T>(trackIndex: number, func: MathHelperFunction<T>, ...args: any[]): T {
        return func(this.tracks[trackIndex].points, ...args)
    }

    applyToRoute<T>(routeIndex: number, func: MathHelperFunction<T>, ...args: any[]): T {
        return func(this.routes[routeIndex].points, ...args)
    }
}
```

You could also make the assumption, for the functional interface, that args is always options, or always assume that the second argument to the math helper function is options, something like that. That could make the code simpler.

Calling it might look like:

```ts
// Calculate distance for the first track
const distance = parsedGPX.applyToTrack(0, calculateDistance);

// Calculate duration for the first track
const duration = parsedGPX.applyToTrack(0, calculateDuration, { avgSpeedThreshold: 0.1 }); // or just pass in the entire options object
```

I'm not claiming this is necessarily the best way, but I think it will reduce unnecessary code.

**Review by We-Gold — CHANGES_REQUESTED** [review]
See previous comment in the conversation

**Comment by We-Gold** [comment]
See my PR to your fork.

**Comment by Its-Just-Nans** [comment]
You could just edit my repo directly !

I just removed

image

**Comment by We-Gold** [comment]
I didn't know I had write access to your repo. Thanks for letting me know.

Headless chrome is no longer working for me, and I'm not exactly sure why. Regular chrome and chromium both work for me. Is headless working for you?

**Comment by Its-Just-Nans** [comment]
Now yes

image


image

**Comment by We-Gold** [comment]
I got a chance to it with webdriverio. I don't know why, but only playwright is working on my machine. This config is working for me. Can you check if it works for you too?

```js
test: {
     browser: {
          provider: 'playwright',
          enabled: true,
          name: 'chromium',
          headless: true,
     },
},
```

**Comment by Its-Just-Nans** [comment]
It's working

```sh
npx playwright install
# playwright told me to install some libs
sudo apt install libavif13 libgst7 
```

image

**Comment by Its-Just-Nans** [comment]
> I didn't know I had write access to your repo. Thanks for letting me know.

image

It's by default when you create a Pull request! ^^

**Review by We-Gold — APPROVED** [review]

**Pull request merged**
