### PR TITLE
Add a `stringifyGPX` method to serialize a ParsedGPX object as XML.

### PR DESCRIPTION
**Pull request by bdferris-v2**
As discussed in issue #9.

### CODE REVIEW

**Comment by We-Gold** [comment]
Overall, looks good, I'll make sure to run the tests myself later to make sure everything works for me too. The next improvement to the main functionality of the library (outside of this PR) will probably be rewriting the parsing to be more modular, and this code would provide a solid basis for that functionality.

One request: the parsing feature of the library supports custom parsers, other than the browser-provided parser for use in frameworks like React Native. It would be great if this stringification feature also supported that. A glance at the [xmldom-qsa](https://www.npmjs.com/package/xmldom-qsa) (the library I've been testing with) README reveals that a custom XMLSerializer is available through the library.

Edit: Confirmed that the tests pass locally. I realized it would also be great if the PR could include some documentation for this feature in the README as well.

**Comment by bdferris-v2** [comment]
Cool, I update README.md and index.ts with details on `stringifyGPX`.  I also added support for a custom XMLSerializer.  Let me know if that's what you had in mind.

**Comment by We-Gold** [comment]
Yep, that's what I was aiming for. 

However, I believe the line in the README where you show how to use the custom serializer has a bug. 

Rather than

```js
const xml = stringifyGPX(parsedFile, customXmlSerializer = new XMLSerializer());
```

it should be

```js
const xml = stringifyGPX(parsedFile, new XMLSerializer());
```

Otherwise, it will throw an error saying "customXmlSerializer is not defined" unless you previously defined it. 

Also, could you add another test like this to test the case with a custom parser? 

```js
test("converts ParsedGPX to string", () => {
    const [gpx, error] = parseGPX(testGPXFile);
    const xml = stringifyGPX(gpx, new XMLSerializer()); // <-- This is imported from xmldom-qsa
    expect(prettyPrintXml(xml)).toEqual(prettyPrintXml(EXPECTED_XML));
})
```

Thanks!

**Comment by bdferris-v2** [comment]
Done and done.

**Review by We-Gold — APPROVED** [review]

**Pull request merged**
